trigger:
- master

variables:
  azureSubscription: 'ConexaoAzureStudents'
  dockerRegistryServiceConnection: 'ConexaoACR' 
  acrName: 'acrsprint4vitor'                    
  webAppName: 'app-sprint4-vitor'                 
  resourceGroup: 'rg-sprint4-fiap'              
  imageName: 'minhaapioracle'                  
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  vmImageName: 'ubuntu-latest'
  tag: '$(Build.BuildId)'

stages:
- stage: CI_Build_e_Test
  displayName: 'Estágio 1: Build, Teste e Push (CI)'
  jobs:
  - job: BuildAndTest
    displayName: 'Build, Test e Push da Imagem Docker'
    pool:
      vmImage: $(vmImageName)
    
    steps:
    - task: Docker@2
      displayName: 'Build da imagem Docker'
      inputs:
        command: 'build'
        repository: '$(imageName)'
        dockerfile: '$(dockerfilePath)'
        containerRegistry: '$(dockerRegistryServiceConnection)' 
        tags: |
          $(tag)
          latest
  
    - script: |
        echo "Iniciando etapa de testes..."
        # (Aqui entrariam os comandos 'dotnet test', se houvesse um projeto de teste)
        echo "Testes concluídos com sucesso (simulado)."
      displayName: 'Executar Testes (Simulado)'

    - task: PublishTestResults@2
      displayName: 'Publicar Resultados de Teste (Simulado)'
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/TEST-*.xml' 
        failTaskOnFailedTests: true
    - task: Docker@2
      displayName: 'Push da imagem para o ACR'
      inputs:
        command: 'push'
        repository: '$(imageName)'
        containerRegistry: '$(dockerRegistryServiceConnection)'
        tags: |
          $(tag)
          latest

- stage: CD_Deploy
  displayName: 'Estágio 2: Deploy no Web App (CD)'
  dependsOn: CI_Build_e_Test 
  condition: succeeded()
  
  jobs:
  - job: Deploy
    displayName: 'Deploy no Azure Web App for Containers'
    pool:
      vmImage: $(vmImageName)
      
    steps:
    - task: AzureWebAppContainer@1
      displayName: 'Deploy: Azure Web App'
      inputs:
        azureSubscription: '$(azureSubscription)'
        appName: '$(webAppName)'
        resourceGroupName: '$(resourceGroup)'
        imageName: '$(acrName).azurecr.io/$(imageName):$(tag)' 
        

