trigger:
  branches:
    include:
    - main 
  paths:
    include:
    - MinhaApiOracle/* 
    - README.md         
    - azure-pipelines.yml 
    - Dockerfile        
    - "*.csproj"        


variables:
  azureSubscription: 'ConexaoAzureStudents'
  dockerRegistryServiceConnection: 'ConexaoACR'
  webAppName: 'app-sprint4-vitor'
  containerRegistry: 'acrsprint4vitor.azurecr.io'
  resourceGroup: 'rg-sprint4-fiap'
  imageRepository: 'minhaapioracle'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)' 
  vmImageName: 'ubuntu-latest'
  buildConfiguration: 'Release'

stages:
- stage: CI_Build
  displayName: 'Estágio 1: Build, Teste e Push (CI)'
  jobs:
  - job: BuildAndTest
    displayName: 'Build, Teste e Push da Imagem Docker'
    pool:
      vmImage: $(vmImageName)

    steps:

    - task: Docker@2
      displayName: 'Build da imagem Docker'
      inputs:
        command: 'build'
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        buildContext: '$(Build.SourcesDirectory)'
        tags: |
          $(tag)
          latest

    - task: PublishTestResults@2
      displayName: 'Publicar Resultados de Teste (Simulado)'
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/TEST-*.xml'
        failTaskOnFailedTests: false
      continueOnError: true
    - task: Docker@2
      displayName: 'Push da imagem para o ACR'
      inputs:
        command: 'push'
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        tags: |
          $(tag)
          latest

- stage: CD_Deploy
  displayName: 'Estágio 2: Deploy no Web App (CD)'
  dependsOn: CI_Build
  condition: succeeded()

  jobs:
  - job: Deploy
    displayName: 'Deploy no Azure Web App for Containers'
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: AzureWebAppContainer@1
      displayName: 'Deploy: Azure Web App'
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(webAppName)
        resourceGroupName: $(resourceGroup)
        imageName: '$(containerRegistry)/$(imageRepository):$(tag)'
